#!/usr/bin/env bash
# Regenerate Cloudflare IP allow/realip snippets from cloudflare.com
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALLOW_FILE="$REPO_ROOT/docs/nginx-cloudflare-allow.conf"
REALIP_FILE="$REPO_ROOT/docs/nginx-cloudflare-realip.conf"

V4=$(curl -fsSL https://www.cloudflare.com/ips-v4)
V6=$(curl -fsSL https://www.cloudflare.com/ips-v6)

{
  echo "# Cloudflare IPv4 — allow only proxied traffic from these ranges."
  echo "# Auto-generated by scripts/update-cloudflare-ips.sh"
  echo "# Source: https://www.cloudflare.com/ips-v4"
  echo ""
  while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "allow $cidr;"
  done <<< "$V4"
  echo ""
  echo "# Cloudflare IPv6"
  while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "allow $cidr;"
  done <<< "$V6"
  echo ""
  echo "# Local health checks from the VPS itself"
  echo "allow 127.0.0.1;"
  echo "allow ::1;"
  echo ""
  echo "deny all;"
} > "$ALLOW_FILE"

{
  echo "# Restore real visitor IP when traffic is proxied through Cloudflare."
  echo "# Auto-generated by scripts/update-cloudflare-ips.sh"
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo ""
  while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done <<< "$V4"
  echo ""
  while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done <<< "$V6"
} > "$REALIP_FILE"

echo "Updated:"
echo "  $ALLOW_FILE"
echo "  $REALIP_FILE"
